// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModuleValidateAndParseAddressModuleLessNamespace {
    export interface IModuleValidateAndParseAddressModuleLess {
        error: string;
        ok: string;
    }
}

declare const ModuleValidateAndParseAddressModuleLessModule: ModuleValidateAndParseAddressModuleLessNamespace.IModuleValidateAndParseAddressModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModuleValidateAndParseAddressModuleLessNamespace.IModuleValidateAndParseAddressModuleLess;
};

export = ModuleValidateAndParseAddressModuleLessModule;
