// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModuleInstancePoolModuleLessNamespace {
    export interface IModuleInstancePoolModuleLess {
        poolContainer: string;
        poolContainerInput: string;
        poolInfo: string;
    }
}

declare const ModuleInstancePoolModuleLessModule: ModuleInstancePoolModuleLessNamespace.IModuleInstancePoolModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModuleInstancePoolModuleLessNamespace.IModuleInstancePoolModuleLess;
};

export = ModuleInstancePoolModuleLessModule;
