// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModuleCreateAndInitializePoolIfNecessaryModuleLessNamespace {
    export interface IModuleCreateAndInitializePoolIfNecessaryModuleLess {
        inputAddress: string;
    }
}

declare const ModuleCreateAndInitializePoolIfNecessaryModuleLessModule: ModuleCreateAndInitializePoolIfNecessaryModuleLessNamespace.IModuleCreateAndInitializePoolIfNecessaryModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModuleCreateAndInitializePoolIfNecessaryModuleLessNamespace.IModuleCreateAndInitializePoolIfNecessaryModuleLess;
};

export = ModuleCreateAndInitializePoolIfNecessaryModuleLessModule;
