// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModuleHeaderModuleLessNamespace {
    export interface IModuleHeaderModuleLess {
        container: string;
        text: string;
    }
}

declare const ModuleHeaderModuleLessModule: ModuleHeaderModuleLessNamespace.IModuleHeaderModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModuleHeaderModuleLessNamespace.IModuleHeaderModuleLess;
};

export = ModuleHeaderModuleLessModule;
